### ISSUE TITLE
language server misnamed on winx64

### ISSUE THREAD

**Issue by horihel** [gamunu/vscode-opentofu#76]
### Extension Version

v0.2.0

### VS Code Version

Version: 1.89.1 (system setup)
Commit: dc96b837cf6bb4af9cd736aa3af08cf8279f7685
Date: 2024-05-07T05:13:33.891Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.22631

### Operating System

Windows 11 Pro 23H2

### OpenTofu Version

OpenTofu v1.7.1 on windows_amd64

### Steps to Reproduce

- install opentofu
- no intellisense

the reason is that the plugin looks for the language server in `<pluginpath>/bin/terraform-ls.exe` - but the extension installs the language server into `<pluginpath>/bin/terraform.ls` (without .exe) - resulting in "file not found" errors in the log.

### Expected Behavior

- install opentofu
- have intellisense

### Actual Behavior

- no intellisense because language server not found

### Workarounds

you can manually rename the binary (just add .exe) and then it works

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by gamunu** [comment]
@horihel Thank you for reporting this. The newest version should look for the opentofu-ls.exe. Would it be possible that your language server path is configured in the plugin settings?

**Comment by gamunu** [comment]
@horihel I've released the version v0.2.1 and it should fix the path issue
